### ISSUE TITLE
RFE: allow for full override of source / index with the defined defaults in the Global Variables

### ISSUE THREAD

**Issue by FusionFC** [criblpacks/cribl-palo-alto-networks#24]
I receive one data flow where I don't control the "index" and "source" fields and it would be nice to be able to override them directly in the pack with the defaults that I have defined in the Global Variables.  I currently override the fields down stream as I use the Cribl pack in a pre-processing pipeline.

**Comment by bdalpe** [comment]
@FusionFC this will be fixed in #18.
